id: P005516
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25758
  title: ཁ་བའི་རྒྱལ་ཁམས།
  author: ''
  volumes:
    7e928394d494493da547d0325e35b592:
      image_group_id: I1KG25760
      title: ''
      volume_number: 1
      total_pages: 264
      base_file: v001.txt
